export interface SubBusinessType {
  id: string;
  name: string;
  keywords: string[];
  schemaTypes?: string[];
  targetAudience?: string;
  primaryConversionGoal?: string;
  blueprintType?: string;
}

export interface IndustryDefinition {
  id: string;
  name: string;
  description: string;
  schemaTypes: string[];
  keywords: string[];
  negativeKeywords?: string[];
  businessTypes: SubBusinessType[];
  defaultAudience: string;
  defaultConversionGoal: string;
}

/**
 * Extensible Industry & Business-Type Taxonomy.
 * Designed to support all commercial categories and easily accept future categories.
 */
export const INDUSTRY_TAXONOMY: IndustryDefinition[] = [
  {
    id: 'interior_architecture',
    name: 'Interior & Architecture',
    description: 'Interior design studios, architecture firms, interior contractors, and spatial planning.',
    schemaTypes: ['HomeAndConstructionBusiness', 'GeneralContractor'],
    keywords: [
      'interior design',
      'interior designer',
      'architecture',
      'architect',
      'architectural design',
      'interior decor',
      'home decor',
      'spatial design',
      'modular kitchen',
      'living room design',
      'commercial interior',
      'residential interior',
      'fitout',
      'renovation',
      'turnkey interior',
      'interior contractor',
      'urban planning',
      'landscape architecture',
      'building design',
    ],
    businessTypes: [
      {
        id: 'interior_design_studio',
        name: 'Interior Design Studio',
        keywords: ['interior design', 'interior decorator', 'home decor', 'living room design', 'modular kitchen', 'residential interior', 'interior studio'],
        targetAudience: 'Homeowners, property developers, and commercial space owners looking for interior transformations.',
        primaryConversionGoal: 'Book a design consultation or request a project quotation.',
        blueprintType: 'interior_design',
      },
      {
        id: 'architecture_firm',
        name: 'Architecture Firm',
        keywords: ['architecture', 'architectural design', 'architect', 'urban planning', 'building design', 'master planning', 'structural design'],
        targetAudience: 'Commercial developers, institutions, and high-end residential clients.',
        primaryConversionGoal: 'Schedule an architectural feasibility consultation.',
        blueprintType: 'architecture',
      },
      {
        id: 'interior_contractor',
        name: 'Interior Contractor',
        keywords: ['interior contractor', 'fitout contractor', 'turnkey interior', 'interior execution', 'carpentry fitout'],
        targetAudience: 'Commercial offices, retail spaces, and homeowners requiring turnkey execution.',
        primaryConversionGoal: 'Request a site inspection and estimate.',
        blueprintType: 'interior_contractor',
      },
      {
        id: 'architecture_interior_studio',
        name: 'Architecture & Interior Studio',
        keywords: ['architecture and interior', 'architectural & interior', 'architecture & interior design', 'integrated design studio'],
        targetAudience: 'Clients seeking end-to-end building and interior design synergy.',
        primaryConversionGoal: 'Schedule an integrated design consultation.',
        blueprintType: 'interior_architecture_blended',
      },
    ],
    defaultAudience: 'Property owners, developers, and businesses planning construction or renovation.',
    defaultConversionGoal: 'Request a consultation or portfolio review.',
  },
  {
    id: 'manufacturing',
    name: 'Manufacturing',
    description: 'Industrial manufacturers, pump and machinery producers, fabricators, and OEM suppliers.',
    schemaTypes: ['Corporation', 'Organization', 'LocalBusiness'],
    keywords: [
      'manufacturing',
      'manufacturer',
      'industrial',
      'machining',
      'cnc',
      'fabrication',
      'factory',
      'supplier',
      'oem',
      'production',
      'assembly',
      'pumps',
      'machinery',
      'die casting',
      'sheet metal',
      'casting',
      'forging',
      'engineering components',
      'iso 9001',
      'rfq',
    ],
    businessTypes: [
      {
        id: 'pump_manufacturer',
        name: 'Industrial Pump Manufacturer',
        keywords: ['pump', 'pumps', 'submersible pump', 'centrifugal pump', 'industrial pump', 'hydraulic pump', 'slurry pump', 'dosing pump'],
        targetAudience: 'Procurement engineers, municipal water authorities, and plant managers.',
        primaryConversionGoal: 'Request technical specifications and submit an RFQ.',
        blueprintType: 'pump_manufacturing',
      },
      {
        id: 'machinery_manufacturer',
        name: 'Machinery Manufacturer',
        keywords: ['machinery', 'machine tools', 'heavy machinery', 'cnc machines', 'industrial equipment', 'automation machinery', 'press machinery'],
        targetAudience: 'Plant operations directors and manufacturing facility managers.',
        primaryConversionGoal: 'Download technical datasheet and request equipment pricing.',
        blueprintType: 'machinery_manufacturing',
      },
      {
        id: 'electronics_manufacturer',
        name: 'Electronics Manufacturer',
        keywords: ['electronics manufacturing', 'pcb', 'semiconductors', 'ems', 'circuit board', 'electronic components'],
        targetAudience: 'Hardware engineers, OEMs, and product innovators.',
        primaryConversionGoal: 'Request a manufacturing capability review and quote.',
        blueprintType: 'electronics_manufacturing',
      },
      {
        id: 'auto_parts_manufacturer',
        name: 'Auto Parts Manufacturer',
        keywords: ['auto parts', 'automotive components', 'oem parts', 'vehicle components', 'automotive supplier', 'powertrain parts'],
        targetAudience: 'Tier-1 automotive suppliers and vehicle assemblers.',
        primaryConversionGoal: 'Submit engineering drawings for batch RFQ.',
        blueprintType: 'auto_parts_manufacturing',
      },
      {
        id: 'textile_manufacturer',
        name: 'Textile Manufacturer',
        keywords: ['textile', 'yarn', 'fabric', 'garment manufacturing', 'weaving', 'spinning mill', 'knitting'],
        targetAudience: 'Fashion brands, industrial garment buyers, and wholesale distributors.',
        primaryConversionGoal: 'Request fabric sample catalog and bulk pricing.',
        blueprintType: 'textile_manufacturing',
      },
      {
        id: 'industrial_manufacturer',
        name: 'Industrial Manufacturer',
        keywords: ['industrial manufacturer', 'custom fabrication', 'metal fabrication', 'contract manufacturing', 'precision engineering'],
        targetAudience: 'Industrial procurement teams and contract manufacturing buyers.',
        primaryConversionGoal: 'Request an RFQ quote.',
        blueprintType: 'general_manufacturing',
      },
    ],
    defaultAudience: 'Procurement managers, industrial engineers, and corporate buyers.',
    defaultConversionGoal: 'Submit CAD drawings or request a commercial RFQ.',
  },
  {
    id: 'restaurant_hospitality',
    name: 'Restaurant & Hospitality',
    description: 'Restaurants, cafes, bakeries, bars, catering services, hotels, and food service establishments.',
    schemaTypes: ['Restaurant', 'FoodEstablishment', 'CafeOrCoffeeShop', 'Bakery', 'BarOrPub', 'FastFoodRestaurant', 'Hotel', 'LodgingBusiness'],
    keywords: [
      'restaurant',
      'cafe',
      'bakery',
      'dining',
      'bistro',
      'cuisine',
      'menu',
      'food',
      'coffee',
      'bar & grill',
      'salad',
      'brunch',
      'dessert',
      'culinary',
      'chef',
      'catering',
      'hotel',
      'hospitality',
      'reservations',
      'table booking',
      'order online',
    ],
    businessTypes: [
      {
        id: 'restaurant',
        name: 'Restaurant',
        keywords: [
          'restaurant', 'dining', 'bistro', 'cuisine', 'fine dining', 'eatery',
          'bar and grill', 'steakhouse', 'seafood', 'salad', 'salads', 'bowls',
          'warm bowls', 'healthy food', 'fast casual', 'organic meals', 'lunch',
          'dinner', 'takeout', 'pickup', 'order online', 'chef', 'menu', 'food'
        ],
        schemaTypes: ['Restaurant', 'FoodEstablishment'],
        targetAudience: 'Food lovers, diners, and private event planners.',
        primaryConversionGoal: 'Reserve a table or order online.',
        blueprintType: 'restaurant',
      },
      {
        id: 'cafe',
        name: 'Cafe & Coffee Shop',
        keywords: ['cafe', 'coffee', 'espresso', 'coffee shop', 'roastery', 'latte', 'cold brew', 'tea lounge'],
        schemaTypes: ['CafeOrCoffeeShop'],
        targetAudience: 'Local coffee enthusiasts, remote workers, and casual visitors.',
        primaryConversionGoal: 'View beverage menu and find cafe location.',
        blueprintType: 'cafe',
      },
      {
        id: 'bakery',
        name: 'Bakery & Patisserie',
        keywords: ['bakery', 'pastries', 'bread', 'cakes', 'patisserie', 'croissant', 'cookies', 'custom cakes'],
        schemaTypes: ['Bakery'],
        targetAudience: 'Dessert lovers, party hosts, and daily bread buyers.',
        primaryConversionGoal: 'Order baked goods or request custom cake consultation.',
        blueprintType: 'bakery',
      },
      {
        id: 'catering',
        name: 'Catering Service',
        keywords: ['catering', 'caterer', 'event catering', 'wedding catering', 'corporate catering', 'buffet service'],
        targetAudience: 'Event organizers, corporate event planners, and couples planning weddings.',
        primaryConversionGoal: 'Request an event catering quote and tasting menu.',
        blueprintType: 'catering',
      },
      {
        id: 'hotel_resort',
        name: 'Hotel & Resort',
        keywords: ['hotel', 'resort', 'lodging', 'suites', 'guest rooms', 'hospitality', 'boutique hotel', 'stay'],
        schemaTypes: ['Hotel', 'LodgingBusiness'],
        targetAudience: 'Business travelers, vacationers, and tourists.',
        primaryConversionGoal: 'Book room dates and check room availability.',
        blueprintType: 'hotel',
      },
      {
        id: 'cloud_kitchen',
        name: 'Cloud Kitchen & Food Delivery',
        keywords: ['cloud kitchen', 'ghost kitchen', 'delivery only', 'virtual kitchen', 'food delivery'],
        targetAudience: 'Online food delivery customers.',
        primaryConversionGoal: 'Place delivery order via mobile app or delivery links.',
        blueprintType: 'cloud_kitchen',
      },
    ],
    defaultAudience: 'Guests, diners, and hospitality seekers.',
    defaultConversionGoal: 'Book reservations or place an order.',
  },
  {
    id: 'real_estate',
    name: 'Real Estate',
    description: 'Real estate agencies, property brokerages, property managers, and commercial leasing.',
    schemaTypes: ['RealEstateAgent', 'RealEstateListing'],
    keywords: [
      'real estate',
      'realtor',
      'realty',
      'property',
      'properties',
      'apartments',
      'villas',
      'condos',
      'homes for sale',
      'property management',
      'leasing',
      'commercial real estate',
      'brokerage',
    ],
    businessTypes: [
      {
        id: 'real_estate_agency',
        name: 'Real Estate Agency',
        keywords: ['real estate agency', 'realtor', 'property broker', 'homes for sale', 'buy property', 'sell home', 'residential real estate'],
        targetAudience: 'Home buyers, sellers, and property investors.',
        primaryConversionGoal: 'Schedule a property viewing or request home valuation.',
        blueprintType: 'real_estate',
      },
      {
        id: 'property_management',
        name: 'Property Management Company',
        keywords: ['property management', 'tenant management', 'leasing services', 'rental management', 'landlord services'],
        targetAudience: 'Property investors and absentee landlords.',
        primaryConversionGoal: 'Request a property management proposal.',
        blueprintType: 'property_management',
      },
    ],
    defaultAudience: 'Buyers, sellers, renters, and property investors.',
    defaultConversionGoal: 'Schedule private showing or valuation.',
  },
  {
    id: 'construction',
    name: 'Construction',
    description: 'General contractors, residential builders, civil engineering, and infrastructure construction.',
    schemaTypes: ['GeneralContractor', 'HomeAndConstructionBusiness'],
    keywords: [
      'construction',
      'general contractor',
      'building contractor',
      'civil engineering',
      'commercial construction',
      'residential construction',
      'home builder',
      'infrastructure',
      'excavation',
      'concrete',
      'structural engineering',
    ],
    businessTypes: [
      {
        id: 'general_contractor',
        name: 'General Commercial Contractor',
        keywords: ['general contractor', 'commercial construction', 'building contractor', 'civil engineering', 'infrastructure construction'],
        targetAudience: 'Commercial developers, architects, and municipal project managers.',
        primaryConversionGoal: 'Submit tender / RFP or request project estimate.',
        blueprintType: 'general_contractor',
      },
      {
        id: 'residential_builder',
        name: 'Residential Home Builder',
        keywords: ['home builder', 'custom homes', 'residential construction', 'home remodeling', 'villa construction'],
        targetAudience: 'Prospective homeowners and custom home builders.',
        primaryConversionGoal: 'Book custom home design and building consultation.',
        blueprintType: 'residential_builder',
      },
    ],
    defaultAudience: 'Project owners, developers, and municipal planners.',
    defaultConversionGoal: 'Request a construction bid or consultation.',
  },
  {
    id: 'dental',
    name: 'Dental',
    description: 'Dentists, orthodontic clinics, pediatric dental care, cosmetic dentistry, and oral surgery.',
    schemaTypes: ['Dentist', 'MedicalBusiness'],
    keywords: [
      'dental',
      'dentist',
      'dentistry',
      'teeth',
      'orthodontics',
      'orthodontist',
      'braces',
      'invisalign',
      'dental implants',
      'teeth whitening',
      'oral surgery',
      'pediatric dentist',
      'root canal',
      'cavity',
      'smile makeover',
    ],
    businessTypes: [
      {
        id: 'dental_clinic',
        name: 'Dental Clinic',
        keywords: ['dental clinic', 'family dentistry', 'general dentist', 'teeth cleaning', 'dental implants', 'cosmetic dentistry'],
        schemaTypes: ['Dentist'],
        targetAudience: 'Families and individuals seeking dental health care.',
        primaryConversionGoal: 'Book a dental appointment online.',
        blueprintType: 'dental_clinic',
      },
      {
        id: 'orthodontics_clinic',
        name: 'Orthodontics Clinic',
        keywords: ['orthodontics', 'orthodontist', 'braces', 'invisalign', 'teeth straightening', 'clear aligners'],
        schemaTypes: ['Dentist'],
        targetAudience: 'Teens and adults seeking smile alignment.',
        primaryConversionGoal: 'Book a free smile consultation.',
        blueprintType: 'orthodontics',
      },
    ],
    defaultAudience: 'Patients seeking oral health and cosmetic dentistry.',
    defaultConversionGoal: 'Book an appointment.',
  },
  {
    id: 'healthcare',
    name: 'Healthcare',
    description: 'Medical clinics, hospitals, physical therapy, specialized medical care, and outpatient centers.',
    schemaTypes: ['MedicalClinic', 'Hospital', 'Physician', 'MedicalBusiness'],
    keywords: [
      'healthcare',
      'medical clinic',
      'doctor',
      'physician',
      'hospital',
      'patient care',
      'outpatient',
      'physical therapy',
      'physiotherapy',
      'chiropractor',
      'dermatology',
      'pediatrics',
      'cardiology',
      'urgent care',
      'telemedicine',
    ],
    businessTypes: [
      {
        id: 'medical_clinic',
        name: 'Medical Clinic',
        keywords: ['medical clinic', 'primary care', 'family medicine', 'urgent care', 'internal medicine', 'doctor consultation'],
        schemaTypes: ['MedicalClinic', 'Physician'],
        targetAudience: 'Patients seeking medical consultations and treatments.',
        primaryConversionGoal: 'Schedule doctor appointment.',
        blueprintType: 'medical_clinic',
      },
      {
        id: 'hospital',
        name: 'Hospital & Medical Center',
        keywords: ['hospital', 'emergency care', 'multi-specialty hospital', 'inpatient care', 'surgery center'],
        schemaTypes: ['Hospital'],
        targetAudience: 'Patients and families requiring acute or specialized care.',
        primaryConversionGoal: 'Find a specialist and book consultation.',
        blueprintType: 'hospital',
      },
      {
        id: 'physical_therapy',
        name: 'Physical Therapy & Rehabilitation',
        keywords: ['physical therapy', 'physiotherapy', 'rehabilitation', 'chiropractic', 'sports medicine', 'pain relief'],
        targetAudience: 'Patients recovering from injury or managing chronic pain.',
        primaryConversionGoal: 'Book initial physical therapy assessment.',
        blueprintType: 'physical_therapy',
      },
    ],
    defaultAudience: 'Patients and caregivers.',
    defaultConversionGoal: 'Book medical appointment.',
  },
  {
    id: 'fitness_wellness',
    name: 'Fitness & Wellness',
    description: 'Gyms, fitness centers, personal training, yoga studios, crossfit, and pilates.',
    schemaTypes: ['HealthClub', 'ExerciseGym', 'SportsActivityLocation'],
    keywords: [
      'fitness',
      'gym',
      'workout',
      'trainer',
      'crossfit',
      'yoga',
      'wellness',
      'bodybuilding',
      'pilates',
      'strength training',
      'personal trainer',
      'group classes',
      'cardio',
      'gym membership',
      'free pass',
    ],
    businessTypes: [
      {
        id: 'gym_fitness_center',
        name: 'Gym & Fitness Center',
        keywords: ['gym', 'fitness center', 'weightlifting', 'crossfit', 'personal training', 'workout facility', 'strength training'],
        targetAudience: 'Fitness enthusiasts and individuals seeking healthy lifestyles.',
        primaryConversionGoal: 'Claim 1-day free pass and join membership.',
        blueprintType: 'gym_fitness',
      },
      {
        id: 'yoga_pilates_studio',
        name: 'Yoga & Pilates Studio',
        keywords: ['yoga studio', 'pilates studio', 'vinyasa', 'hot yoga', 'reformer pilates', 'mindfulness', 'meditation'],
        targetAudience: 'Mindful fitness practitioners and wellness seekers.',
        primaryConversionGoal: 'Book intro class or view class schedule.',
        blueprintType: 'yoga_studio',
      },
    ],
    defaultAudience: 'Individuals seeking athletic fitness and wellness.',
    defaultConversionGoal: 'Claim trial pass or sign up for classes.',
  },
  {
    id: 'technology_saas',
    name: 'Technology / SaaS',
    description: 'Software platforms, SaaS products, cloud services, and IT consulting agencies.',
    schemaTypes: ['SoftwareApplication', 'TechArticle'],
    keywords: [
      'saas',
      'software',
      'cloud software',
      'platform',
      'api',
      'developer',
      'integration',
      'pricing plan',
      'sign up free',
      'start trial',
      'crm',
      'enterprise software',
      'it services',
      'cloud solutions',
      'cybersecurity',
      'app',
      'artificial intelligence',
      'machine learning',
    ],
    businessTypes: [
      {
        id: 'saas_platform',
        name: 'SaaS Platform',
        keywords: ['saas', 'software as a service', 'cloud platform', 'start free trial', 'software pricing', 'api documentation', 'product demo'],
        targetAudience: 'Businesses, developers, and product teams.',
        primaryConversionGoal: 'Start free trial or book a live product demo.',
        blueprintType: 'saas_platform',
      },
      {
        id: 'it_services_consulting',
        name: 'IT Services & Consulting',
        keywords: ['it services', 'software development', 'cloud consulting', 'cybersecurity consulting', 'managed it', 'devops consulting'],
        targetAudience: 'Enterprises and growing businesses needing tech solutions.',
        primaryConversionGoal: 'Schedule an IT architecture consultation.',
        blueprintType: 'it_services',
      },
    ],
    defaultAudience: 'Tech leaders, business buyers, and software users.',
    defaultConversionGoal: 'Start trial or schedule demo.',
  },
  {
    id: 'ecommerce',
    name: 'E-commerce',
    description: 'Online retail stores, direct-to-consumer (DTC) brands, and digital marketplaces.',
    schemaTypes: ['Store', 'OnlineStore', 'Product', 'Offer'],
    keywords: [
      'ecommerce',
      'e-commerce',
      'add to cart',
      'shopping cart',
      'checkout',
      'buy online',
      'shipping',
      'free delivery',
      'online store',
      'apparel',
      'retail',
      'catalog',
      'shop now',
      'best sellers',
    ],
    businessTypes: [
      {
        id: 'online_retail_store',
        name: 'Online Retail Store',
        keywords: ['online store', 'ecommerce shop', 'buy online', 'add to cart', 'direct to consumer', 'shop now', 'product catalog'],
        targetAudience: 'Online shoppers and product consumers.',
        primaryConversionGoal: 'Browse products and complete checkout.',
        blueprintType: 'ecommerce_store',
      },
    ],
    defaultAudience: 'Online consumers and shoppers.',
    defaultConversionGoal: 'Browse catalog and make a purchase.',
  },
  {
    id: 'legal',
    name: 'Legal',
    description: 'Law firms, attorneys, advocates, solicitors, and legal advisory practices.',
    schemaTypes: ['LegalService', 'Attorney'],
    keywords: [
      'legal',
      'law firm',
      'attorney',
      'lawyer',
      'legal counsel',
      'advocate',
      'litigation',
      'corporate law',
      'personal injury',
      'criminal defense',
      'family law',
      'immigration lawyer',
      'practice areas',
      'case evaluation',
    ],
    businessTypes: [
      {
        id: 'law_firm',
        name: 'Law Firm',
        keywords: ['law firm', 'attorneys', 'lawyers', 'legal counsel', 'litigation', 'corporate law', 'practice areas'],
        schemaTypes: ['LegalService', 'Attorney'],
        targetAudience: 'Individuals and businesses requiring legal representation.',
        primaryConversionGoal: 'Request a confidential case evaluation.',
        blueprintType: 'legal_firm',
      },
    ],
    defaultAudience: 'Clients seeking legal advice or litigation representation.',
    defaultConversionGoal: 'Request confidential case consultation.',
  },
  {
    id: 'finance',
    name: 'Finance',
    description: 'Accounting firms, CPAs, wealth management, financial advisors, and tax consultancies.',
    schemaTypes: ['FinancialService', 'AccountingService', 'BankOrCreditUnion'],
    keywords: [
      'finance',
      'financial',
      'accounting',
      'cpa',
      'tax preparation',
      'bookkeeping',
      'wealth management',
      'financial advisor',
      'investment advisory',
      'audit',
      'tax planning',
      'payroll services',
      'asset management',
    ],
    businessTypes: [
      {
        id: 'accounting_tax_firm',
        name: 'Accounting & Tax Advisory',
        keywords: ['accounting', 'cpa', 'tax preparation', 'bookkeeping', 'tax planning', 'auditing services', 'payroll'],
        schemaTypes: ['AccountingService'],
        targetAudience: 'Small businesses and high-net-worth individuals.',
        primaryConversionGoal: 'Schedule tax & accounting consultation.',
        blueprintType: 'accounting_finance',
      },
      {
        id: 'financial_wealth_advisory',
        name: 'Financial Advisory & Wealth Management',
        keywords: ['wealth management', 'financial advisor', 'retirement planning', 'investment advisory', 'asset management'],
        schemaTypes: ['FinancialService'],
        targetAudience: 'Families, executives, and retirees planning investments.',
        primaryConversionGoal: 'Book retirement / wealth strategy session.',
        blueprintType: 'wealth_management',
      },
    ],
    defaultAudience: 'Business owners and individuals seeking financial advisory.',
    defaultConversionGoal: 'Book a financial strategy consultation.',
  },
  {
    id: 'beauty_salon',
    name: 'Beauty & Salon',
    description: 'Hair salons, spas, nail salons, aesthetic clinics, and beauty studios.',
    schemaTypes: ['BeautySalon', 'HairSalon', 'DaySpa'],
    keywords: [
      'salon',
      'hair salon',
      'haircut',
      'hairstylist',
      'beauty salon',
      'spa',
      'day spa',
      'massage',
      'facial',
      'manicure',
      'pedicure',
      'skincare',
      'eyebrows',
      'waxing',
      'bridal makeup',
    ],
    businessTypes: [
      {
        id: 'hair_beauty_salon',
        name: 'Hair & Beauty Salon',
        keywords: ['hair salon', 'beauty salon', 'haircut', 'hair color', 'balayage', 'makeup', 'hairstylist'],
        schemaTypes: ['HairSalon', 'BeautySalon'],
        targetAudience: 'Clients seeking hair, makeup, and beauty styling.',
        primaryConversionGoal: 'Book salon appointment.',
        blueprintType: 'beauty_salon',
      },
      {
        id: 'spa_wellness',
        name: 'Spa & Wellness Sanctuary',
        keywords: ['spa', 'day spa', 'massage therapy', 'facials', 'body treatments', 'sauna', 'hydrotherapy'],
        schemaTypes: ['DaySpa'],
        targetAudience: 'Individuals seeking relaxation and aesthetic skin care.',
        primaryConversionGoal: 'Book spa package or massage.',
        blueprintType: 'spa_wellness',
      },
    ],
    defaultAudience: 'Clients seeking hair, skin, and relaxation treatments.',
    defaultConversionGoal: 'Book service appointment.',
  },
  {
    id: 'home_services',
    name: 'Home Services',
    description: 'Plumbing, HVAC, electrical, roofing, pest control, and residential repair contractors.',
    schemaTypes: ['Plumber', 'Electrician', 'HVACBusiness', 'RoofingContractor', 'HomeAndConstructionBusiness'],
    keywords: [
      'plumbing',
      'plumber',
      'hvac',
      'air conditioning',
      'heating and cooling',
      'electrician',
      'electrical repair',
      'roofing',
      'roof repair',
      'pest control',
      'locksmith',
      'garage door',
      'drain cleaning',
      'water heater',
      'emergency repair',
    ],
    businessTypes: [
      {
        id: 'plumbing_service',
        name: 'Plumbing Service',
        keywords: ['plumbing', 'plumber', 'drain cleaning', 'water heater', 'pipe repair', 'emergency plumbing'],
        schemaTypes: ['Plumber'],
        targetAudience: 'Homeowners and property managers with plumbing needs.',
        primaryConversionGoal: 'Call for emergency plumbing or request quote.',
        blueprintType: 'home_services',
      },
      {
        id: 'hvac_service',
        name: 'HVAC & Climate Control',
        keywords: ['hvac', 'air conditioning', 'heating and cooling', 'ac repair', 'furnace installation', 'duct cleaning'],
        schemaTypes: ['HVACBusiness'],
        targetAudience: 'Homeowners and commercial building managers.',
        primaryConversionGoal: 'Schedule AC / heating service visit.',
        blueprintType: 'home_services',
      },
      {
        id: 'electrical_service',
        name: 'Electrical Contractor',
        keywords: ['electrician', 'electrical repair', 'wiring', 'panel upgrade', 'lighting installation', 'licensed electrician'],
        schemaTypes: ['Electrician'],
        targetAudience: 'Residential and commercial property owners.',
        primaryConversionGoal: 'Request electrician dispatch or estimate.',
        blueprintType: 'home_services',
      },
      {
        id: 'roofing_contractor',
        name: 'Roofing Contractor',
        keywords: ['roofing', 'roof repair', 'shingle replacement', 'commercial roofing', 'gutters', 'siding'],
        schemaTypes: ['RoofingContractor'],
        targetAudience: 'Property owners needing roof inspection and replacement.',
        primaryConversionGoal: 'Book free roof inspection and estimate.',
        blueprintType: 'home_services',
      },
    ],
    defaultAudience: 'Homeowners and property managers.',
    defaultConversionGoal: 'Call now or book service technician.',
  },
  {
    id: 'education',
    name: 'Education',
    description: 'Schools, colleges, universities, online academies, tutoring centers, and vocational training.',
    schemaTypes: ['EducationalOrganization', 'School', 'CollegeOrUniversity'],
    keywords: [
      'education',
      'school',
      'academy',
      'university',
      'college',
      'curriculum',
      'admissions',
      'courses',
      'degree programs',
      'tutoring',
      'training center',
      'faculty',
      'students',
      'campus',
      'enroll',
    ],
    businessTypes: [
      {
        id: 'school_academy',
        name: 'School & Academy',
        keywords: ['school', 'academy', 'k-12', 'elementary school', 'high school', 'curriculum', 'admissions'],
        schemaTypes: ['School'],
        targetAudience: 'Parents and prospective students.',
        primaryConversionGoal: 'Schedule a campus tour and apply for admission.',
        blueprintType: 'education',
      },
      {
        id: 'university_college',
        name: 'University & Higher Education',
        keywords: ['university', 'college', 'higher education', 'undergraduate', 'postgraduate', 'degree programs', 'campus life'],
        schemaTypes: ['CollegeOrUniversity'],
        targetAudience: 'Undergraduate and graduate applicants.',
        primaryConversionGoal: 'Request program brochure and start application.',
        blueprintType: 'education',
      },
      {
        id: 'training_coaching_center',
        name: 'Training & Coaching Institute',
        keywords: ['tutoring', 'coaching center', 'vocational training', 'certification courses', 'test prep', 'skill development'],
        targetAudience: 'Students and career professionals enhancing skills.',
        primaryConversionGoal: 'Enroll in upcoming batch or attend free demo class.',
        blueprintType: 'education',
      },
    ],
    defaultAudience: 'Students, parents, and lifelong learners.',
    defaultConversionGoal: 'Apply now or request course catalog.',
  },
  {
    id: 'automotive',
    name: 'Automotive',
    description: 'Auto repair shops, car dealerships, vehicle detailing, and auto maintenance services.',
    schemaTypes: ['AutoRepair', 'AutoDealer'],
    keywords: [
      'automotive',
      'auto repair',
      'car dealership',
      'mechanic',
      'car service',
      'oil change',
      'brake service',
      'used cars',
      'new cars',
      'auto sales',
      'vehicle inspection',
      'tires',
      'auto detailing',
    ],
    businessTypes: [
      {
        id: 'auto_repair_shop',
        name: 'Auto Repair & Service Center',
        keywords: ['auto repair', 'mechanic', 'car maintenance', 'oil change', 'brake service', 'engine diagnostics', 'tire service'],
        schemaTypes: ['AutoRepair'],
        targetAudience: 'Vehicle owners needing maintenance and repairs.',
        primaryConversionGoal: 'Book service appointment.',
        blueprintType: 'automotive_repair',
      },
      {
        id: 'auto_dealership',
        name: 'Auto Dealership',
        keywords: ['car dealership', 'used cars', 'new cars', 'auto sales', 'vehicle inventory', 'car financing', 'trade in'],
        schemaTypes: ['AutoDealer'],
        targetAudience: 'Car buyers and vehicle traders.',
        primaryConversionGoal: 'Browse inventory and schedule a test drive.',
        blueprintType: 'automotive_dealer',
      },
    ],
    defaultAudience: 'Car owners and automobile buyers.',
    defaultConversionGoal: 'Schedule service or test drive.',
  },
  {
    id: 'travel_tourism',
    name: 'Travel & Tourism',
    description: 'Travel agencies, tour operators, vacation rentals, and adventure guides.',
    schemaTypes: ['TravelAgency', 'TouristInformationCenter'],
    keywords: [
      'travel',
      'tourism',
      'travel agency',
      'tour operator',
      'vacation',
      'holidays',
      'tour packages',
      'flight booking',
      'destination',
      'sightseeing',
      'itinerary',
      'travel guide',
    ],
    businessTypes: [
      {
        id: 'travel_agency',
        name: 'Travel Agency & Tour Operator',
        keywords: ['travel agency', 'tour packages', 'custom vacations', 'guided tours', 'holiday booking', 'flight and hotel packages'],
        targetAudience: 'Vacationers, families, and adventure travelers.',
        primaryConversionGoal: 'Request custom vacation itinerary and quote.',
        blueprintType: 'travel_tourism',
      },
    ],
    defaultAudience: 'Travelers and vacation planners.',
    defaultConversionGoal: 'Book tour package or request itinerary.',
  },
  {
    id: 'nonprofit',
    name: 'Nonprofit',
    description: 'Charities, foundations, NGOs, humanitarian missions, and community organizations.',
    schemaTypes: ['NGO', 'Organization'],
    keywords: [
      'nonprofit',
      'non-profit',
      'charity',
      'foundation',
      'ngo',
      'donate',
      'donation',
      'volunteer',
      'humanitarian',
      'community outreach',
      'philanthropy',
      'fundraising',
      'our mission',
    ],
    businessTypes: [
      {
        id: 'charitable_organization',
        name: 'Nonprofit & Charitable Organization',
        keywords: ['nonprofit', 'charity', 'foundation', 'ngo', 'donate now', 'volunteer program', 'humanitarian aid'],
        targetAudience: 'Donors, volunteers, and community stakeholders.',
        primaryConversionGoal: 'Make a donation or register as a volunteer.',
        blueprintType: 'nonprofit',
      },
    ],
    defaultAudience: 'Donors, community members, and volunteers.',
    defaultConversionGoal: 'Donate or volunteer.',
  },
  {
    id: 'government',
    name: 'Government / Public Service',
    description: 'Municipalities, government departments, civic agencies, and public administration.',
    schemaTypes: ['GovernmentOrganization'],
    keywords: [
      'government',
      'public service',
      'municipality',
      'civic services',
      'city hall',
      'department of',
      'public administration',
      'official portal',
      'permits and licenses',
      'citizen services',
    ],
    businessTypes: [
      {
        id: 'government_agency',
        name: 'Government Agency & Civic Portal',
        keywords: ['government agency', 'municipality', 'city portal', 'public administration', 'citizen services', 'permits'],
        targetAudience: 'Citizens, residents, and local business operators.',
        primaryConversionGoal: 'Access public services, permits, or council information.',
        blueprintType: 'government',
      },
    ],
    defaultAudience: 'Citizens and local residents.',
    defaultConversionGoal: 'Access civic services or portal.',
  },
  {
    id: 'professional_services',
    name: 'Professional Services',
    description: 'Business consulting, marketing & creative agencies, HR advisory, and B2B services.',
    schemaTypes: ['ProfessionalService', 'Organization'],
    keywords: [
      'consulting',
      'agency',
      'marketing agency',
      'digital marketing',
      'business consulting',
      'advisory services',
      'management consulting',
      'hr consulting',
      'branding agency',
      'public relations',
      'market research',
      'b2b services',
    ],
    businessTypes: [
      {
        id: 'business_consulting',
        name: 'Business Consulting Firm',
        keywords: ['business consulting', 'management consulting', 'strategy advisory', 'growth consulting', 'corporate advisory'],
        targetAudience: 'Executives and corporate business leaders.',
        primaryConversionGoal: 'Schedule an exploratory strategy consultation.',
        blueprintType: 'professional_services',
      },
      {
        id: 'marketing_creative_agency',
        name: 'Marketing & Creative Agency',
        keywords: ['marketing agency', 'digital marketing', 'creative agency', 'branding agency', 'seo agency', 'advertising agency'],
        targetAudience: 'Marketing directors and growing brand founders.',
        primaryConversionGoal: 'Request a proposal or audit review.',
        blueprintType: 'professional_services',
      },
    ],
    defaultAudience: 'Corporate decision-makers and business leaders.',
    defaultConversionGoal: 'Schedule exploratory consultation.',
  },
  {
    id: 'other',
    name: 'Other Commercial Industry',
    description: 'Specialized commercial enterprises outside standardized taxonomy categories.',
    schemaTypes: ['LocalBusiness', 'Organization'],
    keywords: ['commercial enterprise', 'custom services', 'specialized business'],
    businessTypes: [
      {
        id: 'commercial_enterprise',
        name: 'Specialized Commercial Enterprise',
        keywords: ['commercial enterprise', 'custom services'],
        targetAudience: 'Commercial clients and consumers.',
        primaryConversionGoal: 'Contact company for service information.',
        blueprintType: 'generic_commercial',
      },
    ],
    defaultAudience: 'Commercial clients and consumers.',
    defaultConversionGoal: 'Contact for inquiries.',
  },
  {
    id: 'unknown',
    name: 'Unknown',
    description: 'Websites with insufficient or unidentifiable business evidence.',
    schemaTypes: [],
    keywords: [],
    businessTypes: [
      {
        id: 'unknown_business',
        name: 'Unknown Business Type',
        keywords: [],
        targetAudience: 'Prospective clients and visitors.',
        primaryConversionGoal: 'Direct consultation inquiry.',
        blueprintType: 'generic_unknown',
      },
    ],
    defaultAudience: 'Prospective clients.',
    defaultConversionGoal: 'Inquiry or consultation.',
  },
];
